### PR TITLE
Add EntityFieldsOpsTests

### PR DESCRIPTION
**Pull request by OlenaSMarchenko**
TC https://trello.com/c/GSbara2D/211-tc0050101-entities-fields-ops-input-new-record
AT https://trello.com/c/fQJ8XzCc/239-at0050101-entity-fields-ops-input-new-record

### CODE REVIEW

**Comment by sviet-ka** [comment]
As far as I remember, we should create a private static final variable for an element if it is used more than once. And you repeat the same elements several times.

**Review by AnastasiiaPV — APPROVED** [review]
LGTM

**Comment by Andrey2694** [comment]
in description should be links on your AT and TC

**Comment by OlenaSMarchenko** [comment]
> in description should be links on your AT and TC

Added, thank you!

**Pull request closed without merging**
