### PR TITLE
AT_007.01.01 | Entity > Import Values > Create Draft Record

### PR DESCRIPTION
**Pull request by VasiliyTsoy**
AT https://trello.com/c/BIHVETf4/846-at0070101-entity-import-values-create-draft-record
TC https://trello.com/c/boytXUMH/844-tc0070101-entity-import-values-create-draft-record
US https://trello.com/c/tCKXniSi/471-us00701-entity-import-values-create-draft-record

### CODE REVIEW

**Review by Stan575 — COMMENTED** [review]
I see only one assert in testCreateDraftRecord()
should created draft data be verified?

**Review by AnastasiiaPV — APPROVED** [review]

**Comment by VasiliyTsoy** [comment]
> I see only one assert in testCreateDraftRecord() should created draft data be verified?

At the beginning of writing the test, I thought that it was not necessary, but after your comment I thought that it would be more correct to check for draft data.Before I write a test and add it to main

**Review by Stan575 — APPROVED** [review]
I approve PR, think how you can improve last test (data verification)

**Comment by VasiliyTsoy** [comment]
> I approve PR, think how you can improve last test (data verification)

ok.

**Pull request merged**
